# Obraz z dependencjami
from dokken/ubuntu-18.04

#Instalowanie wymaganych pakietów
run sudo apt-get update
run sudo apt-get install -y pkg-config
run sudo apt-get install -y ncurses-dev
run sudo apt-get install -y check
run sudo apt-get install -y make
run sudo apt-get install -y cmake
run sudo apt-get install -y git

