version: "3"
services:
  Builder:
    image: build-img
    volumes:
      - build:/build:rw
      - log:/log:rw
      - app:/app:rw
    environment:
      - VERSION=${VERSION}
  Tester:
    image: test-img
    volumes:
      - log:/log:rw
  Deploy:
    image: deploy-img
    container_name: DEPLOY
    volumes:
      - app:/app:rw
    tty: true
    
volumes:
  log:
    name: log
  build:
    name: build
  app:
    name: app
